server:
  port: ${port:8030}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: cc-manage-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.52.225:3308/cc-manage-db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  flyway:
    locations: classpath:db
    # 历史表
    baseline-on-migrate: true
    # 默认1，从0开始可以规避版本1不执行问题
    baseline-version: 0
    # 避免数据被意外清空
    clean-disabled: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml


# 日志级别
logging:
  level:
    root: info

knife4j:
  enable: true
  setting:
    language: zh_cn
#    swagger-model-name: 实体类
  production: false
